name: ${project.name}
version: ${project.version}

main: me.remag501.item.ItemsPlugin
api-version: '1.21'

commands:
  itemsbgs:
    description: Gives a special item (molotov or grenade) to the player.
    usage: /giveitems <molotov|grenade> [amount]
    permission: molotovgrenades.give
    permission-message: You do not have permission to use this command.

permissions:
  molotovgrenades.give:
    description: Allows users to use the /giveitems command.
    default: op

depend:
  - BGSCore